# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - gripper_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    default: true
  gripper_controller:
    type: GripperCommand
    #allowed_execution_duration_scaling: 5.0
    #allowed_goal_duration_margin: 5.0
    joints:
      - rg2_gripper_finger_left_joint
    action_ns: gripper_cmd
    default: true