sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: /filtered_cloud
  max_range: 2.0
  max_update_rate: 2.0
  padding_offset: 0.15
  padding_scale: 1.5
  point_cloud_topic: /camera/depth/color/points
  point_subsample: 4
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater